spring:
    application:
        name: product-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: product-db
    graphql:
        graphiql:
            enabled: true
server:
    port: 8081